# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

kind: Service
apiVersion: v1
metadata:
  name: roberts-helidon-stock-application
  namespace: bobs-books
  labels:
    app: roberts-helidon-stock-application
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: roberts-helidon-stock-application
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: roberts-helidon-stock-application
  namespace: bobs-books
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: roberts-helidon-stock-application
        version: v1
    spec:
      containers:
      - name: roberts-helidon-stock-application
        image: ghcr.io/verrazzano/example-roberts-helidon-stock-application:test
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: roberts-helidon-stock-application
      version: v1
---
