# Copyright (c) 2020, Oracle Corporation and/or its affiliates.
apiVersion: verrazzano.io/v1beta1
kind: VerrazzanoBinding
metadata:
  name: bobs-books-binding
  namespace: default
spec:
  description: "Bob's Books binding"
  modelName: bobs-books-model
  coherenceBindings:
    - name: "bobbys-coherence"
      replicas: 3
    - name: "roberts-coherence"
      replicas: 2
  helidonBindings:
    - name: "roberts-helidon-stock-application"
      replicas: 2
    - name: "bobbys-helidon-stock-application"
      replicas: 3
  weblogicBindings:
    - name: "bobbys-front-end"
      replicas: 1
    - name: "bobs-bookstore"
      replicas: 1
  databaseBindings:
    - name: mysql
      credentials: mysql-credentials
      url: "jdbc:mysql://mysql.bob.svc.default.local:3306/books"
  placement:
    - name: local
      namespaces:
        - name: bobby
          components:
            - name: bobbys-coherence
            - name: bobbys-front-end
            - name: bobbys-helidon-stock-application
        - name: robert
          components:
            - name: roberts-helidon-stock-application
            - name: roberts-coherence
        - name: bob
          components:
            - name: bobs-bookstore
  ingressBindings:
    - name: "bobbys-ingress"
      dnsName: "bobbys-books.example.com"
    - name: "bobs-ingress"
      dnsName: "bobs-books.example.com"
    - name: "roberts-ingress"
      dnsName: "roberts-books.example.com"