# Copyright (c) 2020, Oracle Corporation and/or its affiliates.
---
apiVersion: "weblogic.oracle/v2"
kind: Domain
metadata:
  name: bobs-bookstore
  namespace: bob
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: bobs-bookstore
spec:
  domainHome: /u01/oracle/user_projects/domains/bobs-bookstore
  domainHomeInImage: true
  image: "docker.pkg.github.com/verrazzano/examples/bobs-bookstore-order-manager:0.1.0"
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets:
  - name: "ocir"
  webLogicCredentialsSecret:
    name: bobs-bookstore-weblogic-credentials
  includeServerOutInPodLog: true
  logHomeEnabled: true
  logHome: /u01/oracle/bobs-bookstore/logs
  serverStartPolicy: "IF_NEEDED"
  serverPod:
    env:
      - name: JAVA_OPTIONS
        value: "-Dweblogic.StdoutDebugEnabled=false"
      - name: USER_MEM_ARGS
        value: "-Djava.security.egd=file:/dev/./urandom "
      - name: WL_HOME
        value: /u01/oracle/wlserver
      - name: MW_HOME
        value: /u01/oracle
  adminServer:
    serverStartState: "RUNNING"
    adminService:
      channels:
        - channelName: default
          nodePort: 32401
        - channelName: T3Channel
          nodePort: 32402
  clusters:
    - clusterName: cluster-1
      serverStartState: "RUNNING"
      replicas: 2
---
apiVersion: v1
kind: Secret
metadata:
  name: bobs-bookstore-weblogic-credentials
  namespace: bob
type: Opaque
data:
  password: d2VsY29tZTE=
  username: d2VibG9naWM=
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: bob
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: bob
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        sidecar.istio.io/inject: “false”
    spec:
      containers:
        - image: mysql:8.0.20
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: WebLogic1234
            - name: MYSQL_USER
              value: books
            - name: MYSQL_PASSWORD
              value: WebLogic1234
            - name: MYSQL_DATABASE
              value: books
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
      imagePullSecrets:
        - name: ocir
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: bob
data:
  initdb.sql: |
    alter user 'books'@'%'
    IDENTIFIED WITH mysql_native_password
    BY 'WebLogic1234';
    create table `orders` (
        `id` int not null auto_increment,
        `order_date` date,
        `name` char(40),
        `street` char(40),
        `city` char(40),
        `state` char(2),
        primary key(`id`)
    );
    create table `order_books` (
        `order_id` int,
        `book_id` int,
        `title` char(80),
        foreign key (`order_id`)
        references `orders`(`id`)
        on delete cascade
    );
    insert into `orders` (`id`, `order_date`, `name`, `street`, `city`, `state`)
    values (1, curdate(), "Bob Down", "12 Main Rd", "Mt Everest", "NJ");
    insert into `order_books` (`order_id`, `book_id`, `title`)
    values (1, 2, "Harry Potter");
    insert into `order_books` (`order_id`, `book_id`, `title`)
    values (1, 4, "Twilight");
