package org.todo.services;

import org.todo.services.resource.ItemsResource;

import javax.naming.NamingException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class OracleDBService extends TodoService {
    // Create app table for OracleDB
    private static final String ORACLEDB_CREATE_TABLE = "CREATE TABLE ToDos( " +
            "taskId NUMBER GENERATED BY DEFAULT AS IDENTITY, " +
            "task VARCHAR2(200) NOT NULL, " +
            "completed NUMBER(1) DEFAULT 0 CHECK (completed in (0,1)), " +
            "PRIMARY KEY(taskId));";

    @Override
    public String getCreateTableStatement() {
        return ORACLEDB_CREATE_TABLE;
    }

    @Override
    boolean getComplete(ResultSet resultSet) throws SQLException {
        return (resultSet.getInt("completed") != 0);
    }

    @Override
    public void update(int id, String status) {
        try (Connection conn = ItemsResource.datasource().getConnection()) {
            PreparedStatement statement = conn.prepareStatement(updateSql);
            System.out.println(updateSql);
            statement.setInt(0, completeFromBooleanString(status));
            statement.setLong(1, id);
            statement.executeUpdate();
        } catch (SQLException | NamingException ex) {
            throw new RuntimeException(ex);
        }
    }

    private int completeFromBooleanString(String status) {
        if (status.equalsIgnoreCase("true")) {
            return 1;
        }
        return 0;
    }
}
